// Generated by gencpp from file apc2016/BinToteMoveGoal.msg
// DO NOT EDIT!


#ifndef APC2016_MESSAGE_BINTOTEMOVEGOAL_H
#define APC2016_MESSAGE_BINTOTEMOVEGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace apc2016
{
template <class ContainerAllocator>
struct BinToteMoveGoal_
{
  typedef BinToteMoveGoal_<ContainerAllocator> Type;

  BinToteMoveGoal_()
    : bin()
    , position()
    , fut000(0)
    , kakujiku(0)  {
    }
  BinToteMoveGoal_(const ContainerAllocator& _alloc)
    : bin(_alloc)
    , position(_alloc)
    , fut000(0)
    , kakujiku(0)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _bin_type;
  _bin_type bin;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _position_type;
  _position_type position;

   typedef int32_t _fut000_type;
  _fut000_type fut000;

   typedef int32_t _kakujiku_type;
  _kakujiku_type kakujiku;




  typedef boost::shared_ptr< ::apc2016::BinToteMoveGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::apc2016::BinToteMoveGoal_<ContainerAllocator> const> ConstPtr;

}; // struct BinToteMoveGoal_

typedef ::apc2016::BinToteMoveGoal_<std::allocator<void> > BinToteMoveGoal;

typedef boost::shared_ptr< ::apc2016::BinToteMoveGoal > BinToteMoveGoalPtr;
typedef boost::shared_ptr< ::apc2016::BinToteMoveGoal const> BinToteMoveGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::apc2016::BinToteMoveGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::apc2016::BinToteMoveGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace apc2016

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'apc2016': ['/home/kamiya/data/apc/ros/src/apc2016/msg', '/home/kamiya/data/apc/ros/devel/share/apc2016/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::apc2016::BinToteMoveGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::apc2016::BinToteMoveGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::apc2016::BinToteMoveGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::apc2016::BinToteMoveGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::apc2016::BinToteMoveGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::apc2016::BinToteMoveGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::apc2016::BinToteMoveGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a67a2064427f5ae65b5431650ab9308c";
  }

  static const char* value(const ::apc2016::BinToteMoveGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa67a2064427f5ae6ULL;
  static const uint64_t static_value2 = 0x5b5431650ab9308cULL;
};

template<class ContainerAllocator>
struct DataType< ::apc2016::BinToteMoveGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "apc2016/BinToteMoveGoal";
  }

  static const char* value(const ::apc2016::BinToteMoveGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::apc2016::BinToteMoveGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
string bin\n\
string position\n\
int32 fut000\n\
int32 kakujiku\n\
";
  }

  static const char* value(const ::apc2016::BinToteMoveGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::apc2016::BinToteMoveGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.bin);
      stream.next(m.position);
      stream.next(m.fut000);
      stream.next(m.kakujiku);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct BinToteMoveGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::apc2016::BinToteMoveGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::apc2016::BinToteMoveGoal_<ContainerAllocator>& v)
  {
    s << indent << "bin: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.bin);
    s << indent << "position: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.position);
    s << indent << "fut000: ";
    Printer<int32_t>::stream(s, indent + "  ", v.fut000);
    s << indent << "kakujiku: ";
    Printer<int32_t>::stream(s, indent + "  ", v.kakujiku);
  }
};

} // namespace message_operations
} // namespace ros

#endif // APC2016_MESSAGE_BINTOTEMOVEGOAL_H
