// Generated by gencpp from file apc2016/CalibData.msg
// DO NOT EDIT!


#ifndef APC2016_MESSAGE_CALIBDATA_H
#define APC2016_MESSAGE_CALIBDATA_H

#include <ros/service_traits.h>


#include <apc2016/CalibDataRequest.h>
#include <apc2016/CalibDataResponse.h>


namespace apc2016
{

struct CalibData
{

typedef CalibDataRequest Request;
typedef CalibDataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CalibData
} // namespace apc2016


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::apc2016::CalibData > {
  static const char* value()
  {
    return "235fa1ee243c9be8558993462508698f";
  }

  static const char* value(const ::apc2016::CalibData&) { return value(); }
};

template<>
struct DataType< ::apc2016::CalibData > {
  static const char* value()
  {
    return "apc2016/CalibData";
  }

  static const char* value(const ::apc2016::CalibData&) { return value(); }
};


// service_traits::MD5Sum< ::apc2016::CalibDataRequest> should match 
// service_traits::MD5Sum< ::apc2016::CalibData > 
template<>
struct MD5Sum< ::apc2016::CalibDataRequest>
{
  static const char* value()
  {
    return MD5Sum< ::apc2016::CalibData >::value();
  }
  static const char* value(const ::apc2016::CalibDataRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::apc2016::CalibDataRequest> should match 
// service_traits::DataType< ::apc2016::CalibData > 
template<>
struct DataType< ::apc2016::CalibDataRequest>
{
  static const char* value()
  {
    return DataType< ::apc2016::CalibData >::value();
  }
  static const char* value(const ::apc2016::CalibDataRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::apc2016::CalibDataResponse> should match 
// service_traits::MD5Sum< ::apc2016::CalibData > 
template<>
struct MD5Sum< ::apc2016::CalibDataResponse>
{
  static const char* value()
  {
    return MD5Sum< ::apc2016::CalibData >::value();
  }
  static const char* value(const ::apc2016::CalibDataResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::apc2016::CalibDataResponse> should match 
// service_traits::DataType< ::apc2016::CalibData > 
template<>
struct DataType< ::apc2016::CalibDataResponse>
{
  static const char* value()
  {
    return DataType< ::apc2016::CalibData >::value();
  }
  static const char* value(const ::apc2016::CalibDataResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // APC2016_MESSAGE_CALIBDATA_H
