// Generated by gencpp from file apc2016/CameraSnapshotResponse.msg
// DO NOT EDIT!


#ifndef APC2016_MESSAGE_CAMERASNAPSHOTRESPONSE_H
#define APC2016_MESSAGE_CAMERASNAPSHOTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/PointCloud2.h>
#include <sensor_msgs/Image.h>
#include <sensor_msgs/Image.h>
#include <sensor_msgs/Image.h>
#include <sensor_msgs/PointCloud2.h>
#include <sensor_msgs/Image.h>
#include <sensor_msgs/Image.h>
#include <sensor_msgs/Image.h>
#include <sensor_msgs/Image.h>

namespace apc2016
{
template <class ContainerAllocator>
struct CameraSnapshotResponse_
{
  typedef CameraSnapshotResponse_<ContainerAllocator> Type;

  CameraSnapshotResponse_()
    : fx8_pcl_data()
    , fx8_x_img()
    , fx8_y_img()
    , fx8_z_img()
    , realsense_pcl_data()
    , realsense_rgb_img()
    , realsense_x_img()
    , realsense_y_img()
    , realsense_z_img()  {
    }
  CameraSnapshotResponse_(const ContainerAllocator& _alloc)
    : fx8_pcl_data(_alloc)
    , fx8_x_img(_alloc)
    , fx8_y_img(_alloc)
    , fx8_z_img(_alloc)
    , realsense_pcl_data(_alloc)
    , realsense_rgb_img(_alloc)
    , realsense_x_img(_alloc)
    , realsense_y_img(_alloc)
    , realsense_z_img(_alloc)  {
    }



   typedef  ::sensor_msgs::PointCloud2_<ContainerAllocator>  _fx8_pcl_data_type;
  _fx8_pcl_data_type fx8_pcl_data;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _fx8_x_img_type;
  _fx8_x_img_type fx8_x_img;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _fx8_y_img_type;
  _fx8_y_img_type fx8_y_img;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _fx8_z_img_type;
  _fx8_z_img_type fx8_z_img;

   typedef  ::sensor_msgs::PointCloud2_<ContainerAllocator>  _realsense_pcl_data_type;
  _realsense_pcl_data_type realsense_pcl_data;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _realsense_rgb_img_type;
  _realsense_rgb_img_type realsense_rgb_img;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _realsense_x_img_type;
  _realsense_x_img_type realsense_x_img;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _realsense_y_img_type;
  _realsense_y_img_type realsense_y_img;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _realsense_z_img_type;
  _realsense_z_img_type realsense_z_img;




  typedef boost::shared_ptr< ::apc2016::CameraSnapshotResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::apc2016::CameraSnapshotResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CameraSnapshotResponse_

typedef ::apc2016::CameraSnapshotResponse_<std::allocator<void> > CameraSnapshotResponse;

typedef boost::shared_ptr< ::apc2016::CameraSnapshotResponse > CameraSnapshotResponsePtr;
typedef boost::shared_ptr< ::apc2016::CameraSnapshotResponse const> CameraSnapshotResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::apc2016::CameraSnapshotResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::apc2016::CameraSnapshotResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace apc2016

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'apc2016': ['/home/kamiya/data/apc/ros/src/apc2016/msg', '/home/kamiya/data/apc/ros/devel/share/apc2016/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::apc2016::CameraSnapshotResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::apc2016::CameraSnapshotResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::apc2016::CameraSnapshotResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::apc2016::CameraSnapshotResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::apc2016::CameraSnapshotResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::apc2016::CameraSnapshotResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::apc2016::CameraSnapshotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4a40a587ed6d4af8334c014f2ee29c4f";
  }

  static const char* value(const ::apc2016::CameraSnapshotResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4a40a587ed6d4af8ULL;
  static const uint64_t static_value2 = 0x334c014f2ee29c4fULL;
};

template<class ContainerAllocator>
struct DataType< ::apc2016::CameraSnapshotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "apc2016/CameraSnapshotResponse";
  }

  static const char* value(const ::apc2016::CameraSnapshotResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::apc2016::CameraSnapshotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/PointCloud2 fx8_pcl_data\n\
sensor_msgs/Image fx8_x_img\n\
sensor_msgs/Image fx8_y_img\n\
sensor_msgs/Image fx8_z_img\n\
sensor_msgs/PointCloud2 realsense_pcl_data\n\
sensor_msgs/Image realsense_rgb_img\n\
sensor_msgs/Image realsense_x_img\n\
sensor_msgs/Image realsense_y_img\n\
sensor_msgs/Image realsense_z_img\n\
\n\
\n\
================================================================================\n\
MSG: sensor_msgs/PointCloud2\n\
# This message holds a collection of N-dimensional points, which may\n\
# contain additional information such as normals, intensity, etc. The\n\
# point data is stored as a binary blob, its layout described by the\n\
# contents of the \"fields\" array.\n\
\n\
# The point cloud data may be organized 2d (image-like) or 1d\n\
# (unordered). Point clouds organized as 2d images may be produced by\n\
# camera depth sensors such as stereo or time-of-flight.\n\
\n\
# Time of sensor data acquisition, and the coordinate frame ID (for 3d\n\
# points).\n\
Header header\n\
\n\
# 2D structure of the point cloud. If the cloud is unordered, height is\n\
# 1 and width is the length of the point cloud.\n\
uint32 height\n\
uint32 width\n\
\n\
# Describes the channels and their layout in the binary data blob.\n\
PointField[] fields\n\
\n\
bool    is_bigendian # Is this data bigendian?\n\
uint32  point_step   # Length of a point in bytes\n\
uint32  row_step     # Length of a row in bytes\n\
uint8[] data         # Actual point data, size is (row_step*height)\n\
\n\
bool is_dense        # True if there are no invalid points\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: sensor_msgs/PointField\n\
# This message holds the description of one point entry in the\n\
# PointCloud2 message format.\n\
uint8 INT8    = 1\n\
uint8 UINT8   = 2\n\
uint8 INT16   = 3\n\
uint8 UINT16  = 4\n\
uint8 INT32   = 5\n\
uint8 UINT32  = 6\n\
uint8 FLOAT32 = 7\n\
uint8 FLOAT64 = 8\n\
\n\
string name      # Name of field\n\
uint32 offset    # Offset from start of point struct\n\
uint8  datatype  # Datatype enumeration, see above\n\
uint32 count     # How many elements in the field\n\
\n\
================================================================================\n\
MSG: sensor_msgs/Image\n\
# This message contains an uncompressed image\n\
# (0, 0) is at top-left corner of image\n\
#\n\
\n\
Header header        # Header timestamp should be acquisition time of image\n\
                     # Header frame_id should be optical frame of camera\n\
                     # origin of frame should be optical center of cameara\n\
                     # +x should point to the right in the image\n\
                     # +y should point down in the image\n\
                     # +z should point into to plane of the image\n\
                     # If the frame_id here and the frame_id of the CameraInfo\n\
                     # message associated with the image conflict\n\
                     # the behavior is undefined\n\
\n\
uint32 height         # image height, that is, number of rows\n\
uint32 width          # image width, that is, number of columns\n\
\n\
# The legal values for encoding are in file src/image_encodings.cpp\n\
# If you want to standardize a new string format, join\n\
# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n\
\n\
string encoding       # Encoding of pixels -- channel meaning, ordering, size\n\
                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n\
\n\
uint8 is_bigendian    # is this data bigendian?\n\
uint32 step           # Full row length in bytes\n\
uint8[] data          # actual matrix data, size is (step * rows)\n\
";
  }

  static const char* value(const ::apc2016::CameraSnapshotResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::apc2016::CameraSnapshotResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.fx8_pcl_data);
      stream.next(m.fx8_x_img);
      stream.next(m.fx8_y_img);
      stream.next(m.fx8_z_img);
      stream.next(m.realsense_pcl_data);
      stream.next(m.realsense_rgb_img);
      stream.next(m.realsense_x_img);
      stream.next(m.realsense_y_img);
      stream.next(m.realsense_z_img);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct CameraSnapshotResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::apc2016::CameraSnapshotResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::apc2016::CameraSnapshotResponse_<ContainerAllocator>& v)
  {
    s << indent << "fx8_pcl_data: ";
    s << std::endl;
    Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "  ", v.fx8_pcl_data);
    s << indent << "fx8_x_img: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.fx8_x_img);
    s << indent << "fx8_y_img: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.fx8_y_img);
    s << indent << "fx8_z_img: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.fx8_z_img);
    s << indent << "realsense_pcl_data: ";
    s << std::endl;
    Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "  ", v.realsense_pcl_data);
    s << indent << "realsense_rgb_img: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.realsense_rgb_img);
    s << indent << "realsense_x_img: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.realsense_x_img);
    s << indent << "realsense_y_img: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.realsense_y_img);
    s << indent << "realsense_z_img: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.realsense_z_img);
  }
};

} // namespace message_operations
} // namespace ros

#endif // APC2016_MESSAGE_CAMERASNAPSHOTRESPONSE_H
