// Generated by gencpp from file apc2016/CameraSnapshot.msg
// DO NOT EDIT!


#ifndef APC2016_MESSAGE_CAMERASNAPSHOT_H
#define APC2016_MESSAGE_CAMERASNAPSHOT_H

#include <ros/service_traits.h>


#include <apc2016/CameraSnapshotRequest.h>
#include <apc2016/CameraSnapshotResponse.h>


namespace apc2016
{

struct CameraSnapshot
{

typedef CameraSnapshotRequest Request;
typedef CameraSnapshotResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CameraSnapshot
} // namespace apc2016


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::apc2016::CameraSnapshot > {
  static const char* value()
  {
    return "4a40a587ed6d4af8334c014f2ee29c4f";
  }

  static const char* value(const ::apc2016::CameraSnapshot&) { return value(); }
};

template<>
struct DataType< ::apc2016::CameraSnapshot > {
  static const char* value()
  {
    return "apc2016/CameraSnapshot";
  }

  static const char* value(const ::apc2016::CameraSnapshot&) { return value(); }
};


// service_traits::MD5Sum< ::apc2016::CameraSnapshotRequest> should match 
// service_traits::MD5Sum< ::apc2016::CameraSnapshot > 
template<>
struct MD5Sum< ::apc2016::CameraSnapshotRequest>
{
  static const char* value()
  {
    return MD5Sum< ::apc2016::CameraSnapshot >::value();
  }
  static const char* value(const ::apc2016::CameraSnapshotRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::apc2016::CameraSnapshotRequest> should match 
// service_traits::DataType< ::apc2016::CameraSnapshot > 
template<>
struct DataType< ::apc2016::CameraSnapshotRequest>
{
  static const char* value()
  {
    return DataType< ::apc2016::CameraSnapshot >::value();
  }
  static const char* value(const ::apc2016::CameraSnapshotRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::apc2016::CameraSnapshotResponse> should match 
// service_traits::MD5Sum< ::apc2016::CameraSnapshot > 
template<>
struct MD5Sum< ::apc2016::CameraSnapshotResponse>
{
  static const char* value()
  {
    return MD5Sum< ::apc2016::CameraSnapshot >::value();
  }
  static const char* value(const ::apc2016::CameraSnapshotResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::apc2016::CameraSnapshotResponse> should match 
// service_traits::DataType< ::apc2016::CameraSnapshot > 
template<>
struct DataType< ::apc2016::CameraSnapshotResponse>
{
  static const char* value()
  {
    return DataType< ::apc2016::CameraSnapshot >::value();
  }
  static const char* value(const ::apc2016::CameraSnapshotResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // APC2016_MESSAGE_CAMERASNAPSHOT_H
