// Generated by gencpp from file apc2016/CoordinateTransform.msg
// DO NOT EDIT!


#ifndef APC2016_MESSAGE_COORDINATETRANSFORM_H
#define APC2016_MESSAGE_COORDINATETRANSFORM_H

#include <ros/service_traits.h>


#include <apc2016/CoordinateTransformRequest.h>
#include <apc2016/CoordinateTransformResponse.h>


namespace apc2016
{

struct CoordinateTransform
{

typedef CoordinateTransformRequest Request;
typedef CoordinateTransformResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CoordinateTransform
} // namespace apc2016


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::apc2016::CoordinateTransform > {
  static const char* value()
  {
    return "dd21a4365a104ec2c5f64bb80636cfe7";
  }

  static const char* value(const ::apc2016::CoordinateTransform&) { return value(); }
};

template<>
struct DataType< ::apc2016::CoordinateTransform > {
  static const char* value()
  {
    return "apc2016/CoordinateTransform";
  }

  static const char* value(const ::apc2016::CoordinateTransform&) { return value(); }
};


// service_traits::MD5Sum< ::apc2016::CoordinateTransformRequest> should match 
// service_traits::MD5Sum< ::apc2016::CoordinateTransform > 
template<>
struct MD5Sum< ::apc2016::CoordinateTransformRequest>
{
  static const char* value()
  {
    return MD5Sum< ::apc2016::CoordinateTransform >::value();
  }
  static const char* value(const ::apc2016::CoordinateTransformRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::apc2016::CoordinateTransformRequest> should match 
// service_traits::DataType< ::apc2016::CoordinateTransform > 
template<>
struct DataType< ::apc2016::CoordinateTransformRequest>
{
  static const char* value()
  {
    return DataType< ::apc2016::CoordinateTransform >::value();
  }
  static const char* value(const ::apc2016::CoordinateTransformRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::apc2016::CoordinateTransformResponse> should match 
// service_traits::MD5Sum< ::apc2016::CoordinateTransform > 
template<>
struct MD5Sum< ::apc2016::CoordinateTransformResponse>
{
  static const char* value()
  {
    return MD5Sum< ::apc2016::CoordinateTransform >::value();
  }
  static const char* value(const ::apc2016::CoordinateTransformResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::apc2016::CoordinateTransformResponse> should match 
// service_traits::DataType< ::apc2016::CoordinateTransform > 
template<>
struct DataType< ::apc2016::CoordinateTransformResponse>
{
  static const char* value()
  {
    return DataType< ::apc2016::CoordinateTransform >::value();
  }
  static const char* value(const ::apc2016::CoordinateTransformResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // APC2016_MESSAGE_COORDINATETRANSFORM_H
