// Generated by gencpp from file apc2016/FanucTwist.msg
// DO NOT EDIT!


#ifndef APC2016_MESSAGE_FANUCTWIST_H
#define APC2016_MESSAGE_FANUCTWIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace apc2016
{
template <class ContainerAllocator>
struct FanucTwist_
{
  typedef FanucTwist_<ContainerAllocator> Type;

  FanucTwist_()
    : linear()
    , angular()
    , fut000(0)
    , kakujiku(0)  {
    }
  FanucTwist_(const ContainerAllocator& _alloc)
    : linear(_alloc)
    , angular(_alloc)
    , fut000(0)
    , kakujiku(0)  {
    }



   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _linear_type;
  _linear_type linear;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _angular_type;
  _angular_type angular;

   typedef int32_t _fut000_type;
  _fut000_type fut000;

   typedef int32_t _kakujiku_type;
  _kakujiku_type kakujiku;




  typedef boost::shared_ptr< ::apc2016::FanucTwist_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::apc2016::FanucTwist_<ContainerAllocator> const> ConstPtr;

}; // struct FanucTwist_

typedef ::apc2016::FanucTwist_<std::allocator<void> > FanucTwist;

typedef boost::shared_ptr< ::apc2016::FanucTwist > FanucTwistPtr;
typedef boost::shared_ptr< ::apc2016::FanucTwist const> FanucTwistConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::apc2016::FanucTwist_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::apc2016::FanucTwist_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace apc2016

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'apc2016': ['/home/kamiya/data/apc/ros/src/apc2016/msg', '/home/kamiya/data/apc/ros/devel/share/apc2016/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::apc2016::FanucTwist_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::apc2016::FanucTwist_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::apc2016::FanucTwist_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::apc2016::FanucTwist_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::apc2016::FanucTwist_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::apc2016::FanucTwist_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::apc2016::FanucTwist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8b0f43f073e4c51f29c404ab37e7dbbb";
  }

  static const char* value(const ::apc2016::FanucTwist_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8b0f43f073e4c51fULL;
  static const uint64_t static_value2 = 0x29c404ab37e7dbbbULL;
};

template<class ContainerAllocator>
struct DataType< ::apc2016::FanucTwist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "apc2016/FanucTwist";
  }

  static const char* value(const ::apc2016::FanucTwist_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::apc2016::FanucTwist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Vector3 linear\n\
geometry_msgs/Vector3 angular\n\
int32 fut000\n\
int32 kakujiku\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::apc2016::FanucTwist_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::apc2016::FanucTwist_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.linear);
      stream.next(m.angular);
      stream.next(m.fut000);
      stream.next(m.kakujiku);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct FanucTwist_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::apc2016::FanucTwist_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::apc2016::FanucTwist_<ContainerAllocator>& v)
  {
    s << indent << "linear: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.linear);
    s << indent << "angular: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.angular);
    s << indent << "fut000: ";
    Printer<int32_t>::stream(s, indent + "  ", v.fut000);
    s << indent << "kakujiku: ";
    Printer<int32_t>::stream(s, indent + "  ", v.kakujiku);
  }
};

} // namespace message_operations
} // namespace ros

#endif // APC2016_MESSAGE_FANUCTWIST_H
