// Generated by gencpp from file apc2016/fx8.msg
// DO NOT EDIT!


#ifndef APC2016_MESSAGE_FX8_H
#define APC2016_MESSAGE_FX8_H

#include <ros/service_traits.h>


#include <apc2016/fx8Request.h>
#include <apc2016/fx8Response.h>


namespace apc2016
{

struct fx8
{

typedef fx8Request Request;
typedef fx8Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct fx8
} // namespace apc2016


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::apc2016::fx8 > {
  static const char* value()
  {
    return "7694acd23d1da3ac46f9283c9114bcae";
  }

  static const char* value(const ::apc2016::fx8&) { return value(); }
};

template<>
struct DataType< ::apc2016::fx8 > {
  static const char* value()
  {
    return "apc2016/fx8";
  }

  static const char* value(const ::apc2016::fx8&) { return value(); }
};


// service_traits::MD5Sum< ::apc2016::fx8Request> should match 
// service_traits::MD5Sum< ::apc2016::fx8 > 
template<>
struct MD5Sum< ::apc2016::fx8Request>
{
  static const char* value()
  {
    return MD5Sum< ::apc2016::fx8 >::value();
  }
  static const char* value(const ::apc2016::fx8Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::apc2016::fx8Request> should match 
// service_traits::DataType< ::apc2016::fx8 > 
template<>
struct DataType< ::apc2016::fx8Request>
{
  static const char* value()
  {
    return DataType< ::apc2016::fx8 >::value();
  }
  static const char* value(const ::apc2016::fx8Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::apc2016::fx8Response> should match 
// service_traits::MD5Sum< ::apc2016::fx8 > 
template<>
struct MD5Sum< ::apc2016::fx8Response>
{
  static const char* value()
  {
    return MD5Sum< ::apc2016::fx8 >::value();
  }
  static const char* value(const ::apc2016::fx8Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::apc2016::fx8Response> should match 
// service_traits::DataType< ::apc2016::fx8 > 
template<>
struct DataType< ::apc2016::fx8Response>
{
  static const char* value()
  {
    return DataType< ::apc2016::fx8 >::value();
  }
  static const char* value(const ::apc2016::fx8Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // APC2016_MESSAGE_FX8_H
