// Generated by gencpp from file apc2016/Int2Success.msg
// DO NOT EDIT!


#ifndef APC2016_MESSAGE_INT2SUCCESS_H
#define APC2016_MESSAGE_INT2SUCCESS_H

#include <ros/service_traits.h>


#include <apc2016/Int2SuccessRequest.h>
#include <apc2016/Int2SuccessResponse.h>


namespace apc2016
{

struct Int2Success
{

typedef Int2SuccessRequest Request;
typedef Int2SuccessResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Int2Success
} // namespace apc2016


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::apc2016::Int2Success > {
  static const char* value()
  {
    return "b61ef40d4ee24ceb5d7075b82d99f030";
  }

  static const char* value(const ::apc2016::Int2Success&) { return value(); }
};

template<>
struct DataType< ::apc2016::Int2Success > {
  static const char* value()
  {
    return "apc2016/Int2Success";
  }

  static const char* value(const ::apc2016::Int2Success&) { return value(); }
};


// service_traits::MD5Sum< ::apc2016::Int2SuccessRequest> should match 
// service_traits::MD5Sum< ::apc2016::Int2Success > 
template<>
struct MD5Sum< ::apc2016::Int2SuccessRequest>
{
  static const char* value()
  {
    return MD5Sum< ::apc2016::Int2Success >::value();
  }
  static const char* value(const ::apc2016::Int2SuccessRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::apc2016::Int2SuccessRequest> should match 
// service_traits::DataType< ::apc2016::Int2Success > 
template<>
struct DataType< ::apc2016::Int2SuccessRequest>
{
  static const char* value()
  {
    return DataType< ::apc2016::Int2Success >::value();
  }
  static const char* value(const ::apc2016::Int2SuccessRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::apc2016::Int2SuccessResponse> should match 
// service_traits::MD5Sum< ::apc2016::Int2Success > 
template<>
struct MD5Sum< ::apc2016::Int2SuccessResponse>
{
  static const char* value()
  {
    return MD5Sum< ::apc2016::Int2Success >::value();
  }
  static const char* value(const ::apc2016::Int2SuccessResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::apc2016::Int2SuccessResponse> should match 
// service_traits::DataType< ::apc2016::Int2Success > 
template<>
struct DataType< ::apc2016::Int2SuccessResponse>
{
  static const char* value()
  {
    return DataType< ::apc2016::Int2Success >::value();
  }
  static const char* value(const ::apc2016::Int2SuccessResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // APC2016_MESSAGE_INT2SUCCESS_H
