// Generated by gencpp from file apc2016/ItemPoseEst.msg
// DO NOT EDIT!


#ifndef APC2016_MESSAGE_ITEMPOSEEST_H
#define APC2016_MESSAGE_ITEMPOSEEST_H

#include <ros/service_traits.h>


#include <apc2016/ItemPoseEstRequest.h>
#include <apc2016/ItemPoseEstResponse.h>


namespace apc2016
{

struct ItemPoseEst
{

typedef ItemPoseEstRequest Request;
typedef ItemPoseEstResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ItemPoseEst
} // namespace apc2016


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::apc2016::ItemPoseEst > {
  static const char* value()
  {
    return "5b7803d93fd307db555ccd63568c7e8f";
  }

  static const char* value(const ::apc2016::ItemPoseEst&) { return value(); }
};

template<>
struct DataType< ::apc2016::ItemPoseEst > {
  static const char* value()
  {
    return "apc2016/ItemPoseEst";
  }

  static const char* value(const ::apc2016::ItemPoseEst&) { return value(); }
};


// service_traits::MD5Sum< ::apc2016::ItemPoseEstRequest> should match 
// service_traits::MD5Sum< ::apc2016::ItemPoseEst > 
template<>
struct MD5Sum< ::apc2016::ItemPoseEstRequest>
{
  static const char* value()
  {
    return MD5Sum< ::apc2016::ItemPoseEst >::value();
  }
  static const char* value(const ::apc2016::ItemPoseEstRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::apc2016::ItemPoseEstRequest> should match 
// service_traits::DataType< ::apc2016::ItemPoseEst > 
template<>
struct DataType< ::apc2016::ItemPoseEstRequest>
{
  static const char* value()
  {
    return DataType< ::apc2016::ItemPoseEst >::value();
  }
  static const char* value(const ::apc2016::ItemPoseEstRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::apc2016::ItemPoseEstResponse> should match 
// service_traits::MD5Sum< ::apc2016::ItemPoseEst > 
template<>
struct MD5Sum< ::apc2016::ItemPoseEstResponse>
{
  static const char* value()
  {
    return MD5Sum< ::apc2016::ItemPoseEst >::value();
  }
  static const char* value(const ::apc2016::ItemPoseEstResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::apc2016::ItemPoseEstResponse> should match 
// service_traits::DataType< ::apc2016::ItemPoseEst > 
template<>
struct DataType< ::apc2016::ItemPoseEstResponse>
{
  static const char* value()
  {
    return DataType< ::apc2016::ItemPoseEst >::value();
  }
  static const char* value(const ::apc2016::ItemPoseEstResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // APC2016_MESSAGE_ITEMPOSEEST_H
