// Generated by gencpp from file apc2016/ItemName2Success.msg
// DO NOT EDIT!


#ifndef APC2016_MESSAGE_ITEMNAME2SUCCESS_H
#define APC2016_MESSAGE_ITEMNAME2SUCCESS_H

#include <ros/service_traits.h>


#include <apc2016/ItemName2SuccessRequest.h>
#include <apc2016/ItemName2SuccessResponse.h>


namespace apc2016
{

struct ItemName2Success
{

typedef ItemName2SuccessRequest Request;
typedef ItemName2SuccessResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ItemName2Success
} // namespace apc2016


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::apc2016::ItemName2Success > {
  static const char* value()
  {
    return "4dc5c1ae2e494627977ff6a6eeb914ca";
  }

  static const char* value(const ::apc2016::ItemName2Success&) { return value(); }
};

template<>
struct DataType< ::apc2016::ItemName2Success > {
  static const char* value()
  {
    return "apc2016/ItemName2Success";
  }

  static const char* value(const ::apc2016::ItemName2Success&) { return value(); }
};


// service_traits::MD5Sum< ::apc2016::ItemName2SuccessRequest> should match 
// service_traits::MD5Sum< ::apc2016::ItemName2Success > 
template<>
struct MD5Sum< ::apc2016::ItemName2SuccessRequest>
{
  static const char* value()
  {
    return MD5Sum< ::apc2016::ItemName2Success >::value();
  }
  static const char* value(const ::apc2016::ItemName2SuccessRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::apc2016::ItemName2SuccessRequest> should match 
// service_traits::DataType< ::apc2016::ItemName2Success > 
template<>
struct DataType< ::apc2016::ItemName2SuccessRequest>
{
  static const char* value()
  {
    return DataType< ::apc2016::ItemName2Success >::value();
  }
  static const char* value(const ::apc2016::ItemName2SuccessRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::apc2016::ItemName2SuccessResponse> should match 
// service_traits::MD5Sum< ::apc2016::ItemName2Success > 
template<>
struct MD5Sum< ::apc2016::ItemName2SuccessResponse>
{
  static const char* value()
  {
    return MD5Sum< ::apc2016::ItemName2Success >::value();
  }
  static const char* value(const ::apc2016::ItemName2SuccessResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::apc2016::ItemName2SuccessResponse> should match 
// service_traits::DataType< ::apc2016::ItemName2Success > 
template<>
struct DataType< ::apc2016::ItemName2SuccessResponse>
{
  static const char* value()
  {
    return DataType< ::apc2016::ItemName2Success >::value();
  }
  static const char* value(const ::apc2016::ItemName2SuccessResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // APC2016_MESSAGE_ITEMNAME2SUCCESS_H
