// Generated by gencpp from file apc2016/ItemPoseEstAddData.msg
// DO NOT EDIT!


#ifndef APC2016_MESSAGE_ITEMPOSEESTADDDATA_H
#define APC2016_MESSAGE_ITEMPOSEESTADDDATA_H

#include <ros/service_traits.h>


#include <apc2016/ItemPoseEstAddDataRequest.h>
#include <apc2016/ItemPoseEstAddDataResponse.h>


namespace apc2016
{

struct ItemPoseEstAddData
{

typedef ItemPoseEstAddDataRequest Request;
typedef ItemPoseEstAddDataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ItemPoseEstAddData
} // namespace apc2016


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::apc2016::ItemPoseEstAddData > {
  static const char* value()
  {
    return "801d8cb1e99292e6a60a6f47cbd396d8";
  }

  static const char* value(const ::apc2016::ItemPoseEstAddData&) { return value(); }
};

template<>
struct DataType< ::apc2016::ItemPoseEstAddData > {
  static const char* value()
  {
    return "apc2016/ItemPoseEstAddData";
  }

  static const char* value(const ::apc2016::ItemPoseEstAddData&) { return value(); }
};


// service_traits::MD5Sum< ::apc2016::ItemPoseEstAddDataRequest> should match 
// service_traits::MD5Sum< ::apc2016::ItemPoseEstAddData > 
template<>
struct MD5Sum< ::apc2016::ItemPoseEstAddDataRequest>
{
  static const char* value()
  {
    return MD5Sum< ::apc2016::ItemPoseEstAddData >::value();
  }
  static const char* value(const ::apc2016::ItemPoseEstAddDataRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::apc2016::ItemPoseEstAddDataRequest> should match 
// service_traits::DataType< ::apc2016::ItemPoseEstAddData > 
template<>
struct DataType< ::apc2016::ItemPoseEstAddDataRequest>
{
  static const char* value()
  {
    return DataType< ::apc2016::ItemPoseEstAddData >::value();
  }
  static const char* value(const ::apc2016::ItemPoseEstAddDataRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::apc2016::ItemPoseEstAddDataResponse> should match 
// service_traits::MD5Sum< ::apc2016::ItemPoseEstAddData > 
template<>
struct MD5Sum< ::apc2016::ItemPoseEstAddDataResponse>
{
  static const char* value()
  {
    return MD5Sum< ::apc2016::ItemPoseEstAddData >::value();
  }
  static const char* value(const ::apc2016::ItemPoseEstAddDataResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::apc2016::ItemPoseEstAddDataResponse> should match 
// service_traits::DataType< ::apc2016::ItemPoseEstAddData > 
template<>
struct DataType< ::apc2016::ItemPoseEstAddDataResponse>
{
  static const char* value()
  {
    return DataType< ::apc2016::ItemPoseEstAddData >::value();
  }
  static const char* value(const ::apc2016::ItemPoseEstAddDataResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // APC2016_MESSAGE_ITEMPOSEESTADDDATA_H
