// Generated by gencpp from file apc2016/SegmentationRequest.msg
// DO NOT EDIT!


#ifndef APC2016_MESSAGE_SEGMENTATIONREQUEST_H
#define APC2016_MESSAGE_SEGMENTATIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace apc2016
{
template <class ContainerAllocator>
struct SegmentationRequest_
{
  typedef SegmentationRequest_<ContainerAllocator> Type;

  SegmentationRequest_()
    : items()  {
    }
  SegmentationRequest_(const ContainerAllocator& _alloc)
    : items(_alloc)  {
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _items_type;
  _items_type items;




  typedef boost::shared_ptr< ::apc2016::SegmentationRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::apc2016::SegmentationRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SegmentationRequest_

typedef ::apc2016::SegmentationRequest_<std::allocator<void> > SegmentationRequest;

typedef boost::shared_ptr< ::apc2016::SegmentationRequest > SegmentationRequestPtr;
typedef boost::shared_ptr< ::apc2016::SegmentationRequest const> SegmentationRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::apc2016::SegmentationRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::apc2016::SegmentationRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace apc2016

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'apc2016': ['/home/kamiya/data/apc/ros/src/apc2016/msg', '/home/kamiya/data/apc/ros/devel/share/apc2016/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::apc2016::SegmentationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::apc2016::SegmentationRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::apc2016::SegmentationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::apc2016::SegmentationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::apc2016::SegmentationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::apc2016::SegmentationRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::apc2016::SegmentationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "37e1a2176c4e23e084db76e25c14b0d8";
  }

  static const char* value(const ::apc2016::SegmentationRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x37e1a2176c4e23e0ULL;
  static const uint64_t static_value2 = 0x84db76e25c14b0d8ULL;
};

template<class ContainerAllocator>
struct DataType< ::apc2016::SegmentationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "apc2016/SegmentationRequest";
  }

  static const char* value(const ::apc2016::SegmentationRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::apc2016::SegmentationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] items\n\
";
  }

  static const char* value(const ::apc2016::SegmentationRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::apc2016::SegmentationRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.items);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct SegmentationRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::apc2016::SegmentationRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::apc2016::SegmentationRequest_<ContainerAllocator>& v)
  {
    s << indent << "items[]" << std::endl;
    for (size_t i = 0; i < v.items.size(); ++i)
    {
      s << indent << "  items[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.items[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // APC2016_MESSAGE_SEGMENTATIONREQUEST_H
