// Generated by gencpp from file apc2016/Segmentation.msg
// DO NOT EDIT!


#ifndef APC2016_MESSAGE_SEGMENTATION_H
#define APC2016_MESSAGE_SEGMENTATION_H

#include <ros/service_traits.h>


#include <apc2016/SegmentationRequest.h>
#include <apc2016/SegmentationResponse.h>


namespace apc2016
{

struct Segmentation
{

typedef SegmentationRequest Request;
typedef SegmentationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Segmentation
} // namespace apc2016


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::apc2016::Segmentation > {
  static const char* value()
  {
    return "1833a77e77b31c02d4aea1d5120b1a94";
  }

  static const char* value(const ::apc2016::Segmentation&) { return value(); }
};

template<>
struct DataType< ::apc2016::Segmentation > {
  static const char* value()
  {
    return "apc2016/Segmentation";
  }

  static const char* value(const ::apc2016::Segmentation&) { return value(); }
};


// service_traits::MD5Sum< ::apc2016::SegmentationRequest> should match 
// service_traits::MD5Sum< ::apc2016::Segmentation > 
template<>
struct MD5Sum< ::apc2016::SegmentationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::apc2016::Segmentation >::value();
  }
  static const char* value(const ::apc2016::SegmentationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::apc2016::SegmentationRequest> should match 
// service_traits::DataType< ::apc2016::Segmentation > 
template<>
struct DataType< ::apc2016::SegmentationRequest>
{
  static const char* value()
  {
    return DataType< ::apc2016::Segmentation >::value();
  }
  static const char* value(const ::apc2016::SegmentationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::apc2016::SegmentationResponse> should match 
// service_traits::MD5Sum< ::apc2016::Segmentation > 
template<>
struct MD5Sum< ::apc2016::SegmentationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::apc2016::Segmentation >::value();
  }
  static const char* value(const ::apc2016::SegmentationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::apc2016::SegmentationResponse> should match 
// service_traits::DataType< ::apc2016::Segmentation > 
template<>
struct DataType< ::apc2016::SegmentationResponse>
{
  static const char* value()
  {
    return DataType< ::apc2016::Segmentation >::value();
  }
  static const char* value(const ::apc2016::SegmentationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // APC2016_MESSAGE_SEGMENTATION_H
