// Generated by gencpp from file apc2016/vac_check.msg
// DO NOT EDIT!


#ifndef APC2016_MESSAGE_VAC_CHECK_H
#define APC2016_MESSAGE_VAC_CHECK_H

#include <ros/service_traits.h>


#include <apc2016/vac_checkRequest.h>
#include <apc2016/vac_checkResponse.h>


namespace apc2016
{

struct vac_check
{

typedef vac_checkRequest Request;
typedef vac_checkResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct vac_check
} // namespace apc2016


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::apc2016::vac_check > {
  static const char* value()
  {
    return "94d89d397b9fef00efaf68b9e7b565de";
  }

  static const char* value(const ::apc2016::vac_check&) { return value(); }
};

template<>
struct DataType< ::apc2016::vac_check > {
  static const char* value()
  {
    return "apc2016/vac_check";
  }

  static const char* value(const ::apc2016::vac_check&) { return value(); }
};


// service_traits::MD5Sum< ::apc2016::vac_checkRequest> should match 
// service_traits::MD5Sum< ::apc2016::vac_check > 
template<>
struct MD5Sum< ::apc2016::vac_checkRequest>
{
  static const char* value()
  {
    return MD5Sum< ::apc2016::vac_check >::value();
  }
  static const char* value(const ::apc2016::vac_checkRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::apc2016::vac_checkRequest> should match 
// service_traits::DataType< ::apc2016::vac_check > 
template<>
struct DataType< ::apc2016::vac_checkRequest>
{
  static const char* value()
  {
    return DataType< ::apc2016::vac_check >::value();
  }
  static const char* value(const ::apc2016::vac_checkRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::apc2016::vac_checkResponse> should match 
// service_traits::MD5Sum< ::apc2016::vac_check > 
template<>
struct MD5Sum< ::apc2016::vac_checkResponse>
{
  static const char* value()
  {
    return MD5Sum< ::apc2016::vac_check >::value();
  }
  static const char* value(const ::apc2016::vac_checkResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::apc2016::vac_checkResponse> should match 
// service_traits::DataType< ::apc2016::vac_check > 
template<>
struct DataType< ::apc2016::vac_checkResponse>
{
  static const char* value()
  {
    return DataType< ::apc2016::vac_check >::value();
  }
  static const char* value(const ::apc2016::vac_checkResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // APC2016_MESSAGE_VAC_CHECK_H
